### ISSUE TITLE
Make `wrappers.jumanji_specs_to_dm_env_specs` compatible with PyTrees

### ISSUE THREAD

**Issue by joeryjoery** [instadeepai/jumanji#75]
### Is your feature request related to a problem? Please describe
In `jumanji.wrappers` the conversion of `jumanji.specs` to `dm_env.specs` does not accept general PyTree Nodes. As mentioned in: https://github.com/deepmind/dm_env/issues/10, this should simply be compatible.

### Describe the solution you'd like
Replace the `else` statement within `jumanji.wrappers.jumanji_specs_to_dm_env_specs` on line:465 from this:
```python
def jumanji_specs_to_dm_env_specs(
    spec: Spec,
) -> Union[dm_env.specs.DiscreteArray, dm_env.specs.BoundedArray, dm_env.specs.Array]:
    if isinstance(spec, DiscreteArray):
        ...
    elif: 
        ...
    else:
        raise ValueError(
            f"spec {spec} of type {type(spec)} is not available in a deepmind environment. "
            "Please override the observation_spec or action_spec method to output spec of type "
            "`dm_env.specs.Array`."
        )
```
to something like this:
```python
def jumanji_specs_to_dm_env_specs(
    spec: Spec,
) -> Union[dm_env.specs.DiscreteArray, dm_env.specs.BoundedArray, dm_env.specs.Array]:
    if isinstance(spec, DiscreteArray):
        ...
    elif: 
        ...
    else:
        try:
            # Recursively call this function for nested Specs
            return jax.tree_map(jumanji_specs_to_dm_env_specs, spec)
        except ...:
            raise ValueError(...)
```

**Comment by clement-bonnet** [comment]
Hi @joeryjoery, would [this](https://github.com/instadeepai/jumanji/pull/76) fix your issue?

**Comment by joeryjoery** [comment]
> Hi @joeryjoery, would [this](https://github.com/instadeepai/jumanji/pull/76) fix your issue?

Hey, your solution wouldn't work with `tuple` (also `list`; which shouldn't be used anyway) and would also convert `NamedTuple` to a `dict`.

Why not simply use `tree_map`?

From my experience with dm-reverb and dm-acme, I know that `dict`, `tuple`, and `NamedTuple` should be supported. Only custom `jax`-based PyTree objects interact a bit awkwardly with `dm-tree`.

**Comment by clement-bonnet** [comment]
Sorry if I am not getting this right, but here, the feature is to convert a Jumanji `Spec` to a tree of dm_env specs and not to handle trees of jumanji specs.
Though you could use any pytree to implement this feature, I have made the choice to have a dictionary as the tree so that one can read the spec names as keys.

Therefore the following example now works (taken from the specs_test):
```
class SinglyNested(NamedTuple):
    array: chex.Array
    bounded_array: chex.Array
    multi_discrete_array: chex.Array

singly_nested_spec = Spec(
    SinglyNested,
    "SinglyNestedSpec",
    array=Array((3, 1), jnp.int32),
    bounded_array=BoundedArray((5, 5), jnp.int32, 0, 3),
    multi_discrete_array=MultiDiscreteArray(jnp.array([4, 5]), jnp.int32),
)

dm_specs = jumanji_specs_to_dm_env_specs(singly_nested_spec)

assert dm_specs == {
    "array": dm_env.specs.Array((3, 1), jnp.int32),
    "bounded_array": dm_env.specs.BoundedArray((5, 5), jnp.int32, 0, 3),
    "multi_discrete_array": dm_env.specs.BoundedArray((2,), jnp.int32, 0, [3, 4]),
}
```

Please correct me if I'm wrong but calling `jax.tree_util.tree_map` on the jumanji `Spec` here would preserve the nested structure of the spec and is not what we want since it would not be supported by dm_env that expects a tuple, list or dict.

Let me know if that works for you.

**Comment by clement-bonnet** [comment]
Hey @joeryjoery, we merge the conversion from jumanji nested spec to dm_env dictionary of specs in https://github.com/instadeepai/jumanji/pull/76. The reason why we can't do `tree_map` is that the structure used to implement nested specs is not the same structure we use to implement the object that the spec is meant to describe, e.g. the observation of an environment. For instance, we model environment observations as `NamedTuples` and not dictionaries, so we have to come up with a namedtuple-similar structure for the spec for which we define nodes (can be leaves) and the constructor that produces an observation given the attributes.
This is indeed a new feature of 0.2.x we just released. Please let me know if it makes sense to you and if the PR fixed your issue.

By the way, thanks for raising the issue about `jumanji.__version__` that we just fixed in https://github.com/instadeepai/jumanji/pull/78. :raised_hands: 

Have a great day!

**Comment by joeryjoery** [comment]
Hi @clement-bonnet, thanks for the comment. Your PR allows me to use nested specs, I will need to refactor my code a bit for this but it does achieve what I want. Great work 👍
